export const BRAND_INFO = {
  name: 'House of Nuts',
  tagline: 'Pure Indulgence',
  description: 'Premium Bihar Makhana Direct To Your Doorstep',
  address: 'Garhi Harsaru, Gurugram, Haryana, India',
  phone: '+91 8745883125',
  whatsapp: '8745883125',
  email: 'houseofnutsfoods@gmail.com',
  gstin: '06BBNPH9171E1ZI',
  upiId: '8745883125@ybl',
  fssai: 'Coming Soon',
  mission: 'To deliver premium Bihar Makhana directly to Indian households while promoting healthy and nutritious snacking.',
};

export const PRODUCTS = [
  {
    id: 1,
    name: 'Raw Makhana',
    weight: '135g',
    category: 'Raw Makhana',
    mrp: 332,
    price: 299,
    discount: 10,
    image: '/products/raw-makhana-135.jpg',
    images: ['/products/raw-makhana-135.jpg'],
    packaging: 'Zipper Stand-Up Pouch',
    dimensions: '160×250×40 mm',
    description: 'Premium quality makhana sourced directly from Bihar. Naturally rich in protein, fiber and antioxidants. Perfect for healthy snacking and daily nutrition.',
    fullDescription: 'Experience the purity of premium Bihar Makhana with our Raw Makhana 135g pack. Sourced directly from the farms of Bihar, this natural superfood is carefully selected and hygienically packed to preserve its nutritional value and authentic taste. Rich in protein and fiber, it\'s the perfect complement to your healthy lifestyle.',
    features: [
      '100% Natural',
      'Rich In Protein',
      'Gluten Free',
      'High Fiber',
      'Premium Quality',
      'No Preservatives',
    ],
    shelfLife: '9 Months',
    origin: 'India',
    storage: 'Store in a cool and dry place away from moisture.',
    nutrition: {
      protein: '14g',
      fiber: '1.6g',
      fat: '5.1g',
      carbs: '64.7g',
      calories: '347 kcal',
    },
    reviews: 4.8,
    reviewCount: 234,
    inStock: true,
  },
  {
    id: 2,
    name: 'Raw Makhana',
    weight: '225g',
    category: 'Raw Makhana',
    mrp: 499,
    price: 449,
    discount: 10,
    image: '/products/raw-makhana-225.jpg',
    images: ['/products/raw-makhana-225.jpg'],
    packaging: 'Zipper Stand-Up Pouch',
    dimensions: '180×300×50 mm',
    description: 'Premium handpicked Bihar Makhana packed hygienically for maximum freshness and nutrition.',
    fullDescription: 'Our bestselling 225g Raw Makhana pack is perfect for families and regular consumers. Each makhana seed is carefully handpicked to ensure premium quality. This larger pack provides excellent value while maintaining our commitment to hygiene and freshness.',
    features: [
      'Rich In Protein',
      'Gluten Free',
      'High Fiber',
      'Premium Quality',
      'Hygienically Packed',
      'Direct From Farm',
    ],
    shelfLife: '9 Months',
    origin: 'India',
    storage: 'Store in a cool and dry place away from moisture.',
    nutrition: {
      protein: '14g',
      fiber: '1.6g',
      fat: '5.1g',
      carbs: '64.7g',
      calories: '347 kcal',
    },
    reviews: 4.9,
    reviewCount: 512,
    inStock: true,
  },
  {
    id: 3,
    name: 'Makhana Sprinkle Chips',
    weight: '25g',
    category: 'Flavoured Makhana',
    mrp: 88,
    price: 79,
    discount: 10,
    image: '/products/makhana-chips-25.jpg',
    images: ['/products/makhana-chips-25.jpg'],
    packaging: 'PET Bottle',
    dimensions: '70mm diameter',
    description: 'Light & crispy roasted makhana with natural flavoring. No preservatives, just pure snacking goodness.',
    fullDescription: 'Perfect for on-the-go snacking, our Makhana Sprinkle Chips are roasted, not fried, to give you the perfect crunch without guilt. Packed with protein and fiber, these are ideal for office breaks, travel, or anytime snacking.',
    features: [
      'Roasted Not Fried',
      'No Preservatives',
      'Rich In Protein',
      'Light & Crispy',
      'Healthy Snack',
      'Convenient Packaging',
    ],
    shelfLife: '6 Months',
    origin: 'India',
    storage: 'Store in a cool and dry place.',
    nutrition: {
      protein: '12g',
      fiber: '2g',
      fat: '3g',
      carbs: '70g',
      calories: '350 kcal',
    },
    reviews: 4.6,
    reviewCount: 145,
    inStock: true,
  },
  {
    id: 4,
    name: 'Makhana Sprinkle Chips',
    weight: '45g',
    category: 'Flavoured Makhana',
    mrp: 128,
    price: 115,
    discount: 10,
    image: '/products/makhana-chips-45.jpg',
    images: ['/products/makhana-chips-45.jpg'],
    packaging: 'PET Bottle',
    dimensions: '90mm diameter',
    description: 'Premium packaging with our delicious roasted makhana chips. Gluten-free and rich in protein.',
    fullDescription: 'Get more of the goodness with our 45g Makhana Sprinkle Chips. This larger size offers better value and is perfect for families. Each bite delivers the perfect balance of taste and nutrition with absolutely no preservatives.',
    features: [
      'Premium Packaging',
      'Gluten Free',
      'Rich In Protein',
      'Light & Crispy',
      'No Artificial Colors',
      'Better Value',
    ],
    shelfLife: '6 Months',
    origin: 'India',
    storage: 'Store in a cool and dry place.',
    nutrition: {
      protein: '12g',
      fiber: '2g',
      fat: '3g',
      carbs: '70g',
      calories: '350 kcal',
    },
    reviews: 4.7,
    reviewCount: 189,
    inStock: true,
  },
];

export const BENEFITS = [
  {
    icon: '💪',
    title: 'Rich In Protein',
    description: 'Essential amino acids for muscle growth and recovery',
  },
  {
    icon: '🛡️',
    title: 'Antioxidant Rich',
    description: 'Protects cells from damage and supports immunity',
  },
  {
    icon: '⚖️',
    title: 'Low Fat',
    description: 'Perfect for weight management and healthy diet',
  },
  {
    icon: '✨',
    title: 'Healthy Snacking',
    description: 'Guilt-free, nutritious alternative to processed snacks',
  },
  {
    icon: '🏃',
    title: 'Active Lifestyle',
    description: 'Boost energy naturally with no crash',
  },
  {
    icon: '🌾',
    title: 'Gluten Free',
    description: 'Safe for celiac and gluten-sensitive individuals',
  },
];

export const WHY_CHOOSE = [
  '✅ Premium Bihar Makhana',
  '✅ Rich In Protein',
  '✅ Gluten Free',
  '✅ High Fiber',
  '✅ No Preservatives',
  '✅ Hygienically Packed',
  '✅ Direct From Farm',
];

export const TRUST_POINTS = [
  { icon: '✓', label: 'GST Registered', value: '06BBNPH9171E1ZI' },
  { icon: '🇮🇳', label: 'Made In India', value: 'Proudly Indian' },
  { icon: '🔒', label: 'Secure Payments', value: 'UPI Verified' },
  { icon: '📦', label: 'Premium Quality', value: 'Farm Fresh' },
  { icon: '🚚', label: 'Free Shipping', value: 'Above ₹499' },
];

export const BLOG_POSTS = [
  {
    id: 1,
    title: 'Top 5 Health Benefits of Makhana You Didn\'t Know',
    category: 'Benefits Of Makhana',
    date: '2024-01-15',
    excerpt: 'Discover the amazing health benefits of makhana and why it\'s becoming a favorite among fitness enthusiasts.',
    content: 'Makhana, also known as fox nuts or lotus seeds, is a superfood packed with nutrients...',
    image: '/blog/makhana-benefits.jpg',
  },
  {
    id: 2,
    title: 'Healthy Snacking: The House of Nuts Way',
    category: 'Healthy Snacking',
    date: '2024-01-10',
    excerpt: 'Learn how to incorporate healthy snacking habits into your daily routine with premium makhana.',
    content: 'Healthy snacking doesn\'t have to be boring...',
    image: '/blog/healthy-snacking.jpg',
  },
  {
    id: 3,
    title: 'High Protein Foods: Makhana vs Other Snacks',
    category: 'High Protein Foods',
    date: '2024-01-05',
    excerpt: 'Compare makhana with other popular snacks and see why it\'s the perfect protein-rich choice.',
    content: 'When it comes to high-protein snacking options...',
    image: '/blog/protein-comparison.jpg',
  },
];

export const SHIPPING_INFO = {
  free_above: 499,
  delivery_times: {
    'Delhi NCR': '1–2 Days',
    'North India': '2–4 Days',
    'Rest Of India': '4–7 Days',
  },
  partners: ['Delhivery', 'Blue Dart', 'XpressBees', 'Ecom Express', 'DTDC'],
};

export const DISCOUNT_RULES = [
  { condition: 'First Time', discount: 15, code: 'HELLO15' },
  { condition: 'Buy 2 Items', discount: 5 },
  { condition: 'Buy 3+ Items', discount: 10 },
];
